### ISSUE TITLE
render F12x is missing ending part

### ISSUE THREAD

**Issue by seanyoung** [bengtmartensson/IrpTransmogrifier#223]
I found another issue comparing my rust irp render with IrpTransmogrifier.

This specific command produces an empty render:

```bash
$ ./irptransmogrifier.sh --irp '{37.9k,422}<1,-3|3,-1>((D:3,S:1,F:8,-16)*,(D:3,S:1,E:8,-16))[D:0..7,S:0..1,F:0..255,E:0..255]' render -r -n D=0,F=255,E=255,S=0 --number-repeats 0
[]
```
If I change the value of either `F` or `E`, the result is quite different:
```bash
$ ./irptransmogrifier.sh --irp '{37.9k,422}<1,-3|3,-1>((D:3,S:1,F:8,-16)*,(D:3,S:1,E:8,-16))[D:0..7,S:0..1,F:0..255,E:0..255]' render -r -n D=0,F=255,E=254,S=0 --number-repeats 0
[+422,-1266,+422,-1266,+422,-1266,+422,-1266,+422,-1266,+1266,-422,+1266,-422,+1266,-422,+1266,-422,+1266,-422,+1266,-422,+1266,-7174]
```

It is not clear to me what is happening here, if I change the IRP in any way then it does work.

**Comment by bengtmartensson** [comment]
Sean, thank you very much for this report. As you probably suspect, it is related to the your other issue #222: For a reason I cannot quite recall, an ending sequence (numerically) equal to the repeat is nuked, just a few lines after the previous problem. Again, the fix is obvious. Will get back in a few days.

**Comment by seanyoung** [comment]
> Sean, thank you very much for this report. As you probably suspect, it is related to the your other issue #222 

Ah, now that you mention it, it does look similar! I had not occurred to me :facepalm:
